name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - firebase/**
jobs:
  deploy-firebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase/functions
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 10.x
        uses: actions/setup-node@v3
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: npm install
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      - name: Deploy
        run: ../.github/workflows/deploy-firebase.sh
