name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 10.x
        uses: actions/setup-node@v3
        with:
          node-version: 10.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
        env:
          NODE_ENV: prod
          REACT_APP_SENTRY_RELEASE: ${{ github.sha }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
      - name: Create a release on Sentry
        uses: tclindner/sentry-releases-action@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: quarantine-hero
          SENTRY_PROJECT: quarantine-hero
        with:
          tagName: ${{ github.sha }}
          environment: production
